# container/Dockerfile

FROM python:3.11-slim

WORKDIR /app

COPY back_requirements.txt requirements.txt

RUN pip install --no-cache-dir -r requirements.txt
RUN python -m nltk.downloader punkt stopwords averaged_perceptron_tagger

EXPOSE 8000

CMD ["uvicorn", "back.main:app", "--host", "0.0.0.0", "--port", "8000"]
