version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile_back
    ports:
      - "8000:8000"
    volumes:
      - ../src/back:/app/back
      - ../src/model:/app/model
      - ../data:/app/data
    working_dir: /app
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: Dockerfile_front
    ports:
      - "8501:8501"
    depends_on:
      - api
    volumes:
      - ../src/front:/app/
    working_dir: /app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge