version: '3.9'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile_back
    ports:
      - "8000:8000"
    volumes:
      - ../src/back:/app/back
      - ../src/model:/app/model
      - ../data:/app/data
    working_dir: /app
